# moPPIt: De Novo Generation of Motif-Specific Peptide Binders

# Must set the universe to Docker
universe = docker
docker_image = agitter/moppit:2.10.0-cuda12.8-py3.12

# Set the log, error and output files
log    = logs/moppit_$(Cluster).log
output = logs/moppit_$(Cluster).$(Process).out
error  = logs/moppit_$(Cluster).$(Process).err

# Set the executable to run
executable = moppit.sh
# job_id matches the row in moppit_params.csv for traceability
arguments  = $(job_id) $(length) $(motifs) $(weights) $(n_batches)

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = samples_$(job_id).csv.gz

# We require a machine with a compatible version of the CUDA driver and sufficient memory
require_gpus = (DriverVersion >= 12.8)
gpus_minimum_memory = 20GB

request_cpus = 4
request_gpus = 1
request_memory = 16GB
request_disk = 20GB

# Opt in to using CHTC GPU Lab resources
+WantGPULab = true
+GPUJobLength = "medium"

# Launch one job per row in the parameters file generated locally with generate_params.py
# Columns: job_id,length,motifs,weights,weight_name,n_batches
# Okay to ignore the warning from the unused column
# WARNING: the Queue variable 'weight_name' was unused by condor_submit. Is it a typo?
queue job_id,length,motifs,weights,weight_name,n_batches from moppit_params_head.csv
